my_project_test:
  outputs:
    dev:
      dbname: destination_db
      host: destination_postgres
      pass: secret
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: destination_user
  target: dev
