services:
  postgres-db:
    container_name: postgres_container
    image: postgres:14.17
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
  