version: 2

sources:
  - name: dev
    database: destination_db
    schema: public
    tables:
      - name: stg_farm_productions
        columns:
          - name: Farm_ID
            tests:
              - not_null
              - unique
          - name: Crop_Type
            tests:
              - not_null
          - name: Farm_Area(acres)
            tests:
              - not_null
          - name: Irrigation_Type
            tests:
              - not_null
          - name: Fertilizer_Used(tons)
            tests:
              - not_null
          - name: Pesticide_Used(kg)
            tests:
              - not_null  
          - name: Yield(tons)
            tests:
              - not_null
          - name: Soil_Type
            tests:
              - not_null
          - name: Season
            tests:
              - not_null
          - name: Water_Usage(m3)
            tests:
              - not_null
